### PR TITLE
Windows 10 Support clarification

### PR DESCRIPTION
**Pull request by capaez**
Windows 10 apps are not supported regardless of the technology used to build them.

### CODE REVIEW

**Comment by IdanAdar** [comment]
Doesn't this change make it less explicit?

The intention of the original text was to make it clear no matter how you read it "in your mind" that Analytics is not supported in Windows, not for Cordova nor for native apps.

**Comment by capaez** [comment]
If some technologies used to build Windows 10 apps did support Analytics and others did not, then I would list the specific technologies. Because all do not, there's no reason to list the different technologies that can be used to build Windows 10 apps.

**Comment by IdanAdar** [comment]
What technologies are you referring to? This page is specifically and only about MobileFirst Analytics, that does not support native or Cordova-based apps.

**Comment by capaez** [comment]
The technologies I was referring to are: Native or Cordova for Windows 10. I understand this page is specific to MobileFirst Analytics, that's not the point I was making. 
Removing "native or Cordova" does make it less explicit, but imo makes it clearer because Windows 10 apps are not supported by MF Analytics regarless of technology used to build the app.

**Pull request merged**
