### PR TITLE
Added MFPF version

### PR DESCRIPTION
**Pull request by MaurizioLuinetti**
This work applies to version 7.x

### CODE REVIEW

**Comment by IdanAdar** [comment]
@MaurizioLuinetti, please sync your fork with the recent changes to resolve the conflicts.

**Comment by IdanAdar** [comment]
I still see conflicts... did you sync your fork?

**Comment by MaurizioLuinetti** [comment]
@IdanAdar, Yes I sync and I see the changes in the server repo

**Comment by MaurizioLuinetti** [comment]
I manually resolved the conflicts, hopefully the result will be OK, otherwise I'll repeat the change. Thanks

**Pull request merged**
